### ISSUE TITLE
Short-Term Roadmap

### ISSUE THREAD

**Issue by mristin** [Parquery/icontract#53]
- [ ] Rename `pre`, `post` and `inv` to `requires`, `ensures` and `invariant`, respectively  
- [ ] Refactor icontract to use `@pre(lambda P: ...)` and `@post(lambda P, result: ...)` to avoid name conflicts with function arguments
- [x] Repalce `repr_args` with `error` argument to the contract
- [x] Add `O` argument for a shallow copy of "old" argument values to `@ensures`
- [ ] Release the version 2 as icontract2 pypi package containing icontract2 module
- [ ] add doctests for the invariant
- [ ] Adapt pyicontract-linter to use icontract2 (and bump its version to 2)
- [ ] Adapt sphinx-icontract to use icontract2 (and bump its version to 2)

Autodoc
- [ ] Wrap `__doc__` with a property getter.
- [ ] Add `enabled` property to `_Contract`. Assign contracts to `__preconditions__` and `__postconditions__` of the original function (
or `fget` in case of properties) even if the contracts are not enabled. `__doc__` wrapper reads from these dunders to assemble the documentation.
- [ ] Allow contracts with `None` conditions so that informal contracts can also be added to `__doc__` (and inherited through classes). 

Transpiler
- [ ] Implement the transpilation tool

**Comment by mristin** [comment]
It turned out that we can not hack around ``help()`` to inject contract information since ``help()`` operates on types of the instances and not on instances itself (see https://groups.google.com/forum/#!topic/python-ideas/c9ntrVuh6WE).

It also turned out that introducing `P` did not make the code more readable -- actually, the code was less readable.

The transpiler tool caused a lot of confusion misleading people to think that a transpilation step is necessary rather than optional. Hence we removed the idea from the short-term plan.
